better CIM compliance and proper formatted config
egnyte/secure-and-govern-for-splunk pull request #1
Opened 2023-02-13 11:22 UTC by michael-nextpart

2023-05-22 10:25 UTC, shethankit requested changes

2023-05-22 10:25 UTC, shethankit commented on src/Egnyte_Protect/default/app.conf
> +state = enabled
By Default State is always enabled and is_configured is always set to false.

2023-05-22 10:25 UTC, shethankit commented on src/TA-egnyte-protect/default/props.conf
> +)
We can not update the severity flags according to this as the severity flags needs to be aligned with Egnyte S&G's UI. And the current values are aligned according to the severity is been categorised in the Egnyte UI.

2023-05-22 10:25 UTC, shethankit commented on src/TA-egnyte-protect/default/app.conf
> +show_in_nav = false
Egnyte S&G needs to be visible in the Nav so, `show_in_nav` needs to be set to true.

2023-07-27 16:08 UTC, michael-nextpart commented on src/TA-egnyte-protect/default/props.conf
> +)
Splunk CIM has 5 severity levels which should be reflected here... no need to correlate with the source system severity system as this should fit into the overall severity scoring of the SIEM.

2023-07-27 16:09 UTC, michael-nextpart commented on src/TA-egnyte-protect/default/app.conf
> +show_in_nav = false
visible yes but best practice is to make Technical add-ons just accessible via the application management and not take space in the launcher side bar.

2023-11-29 08:38 UTC, merged